apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2019-12-05T22:59:11-05:00"
    stack.appsody.dev/authors: Erin Schnabel <schnabel@us.ibm.com>, Ozzy <ozzy@ca.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2019-12-03T16:32:12Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: appsody/java-spring-boot2:0.3.19
    stack.appsody.dev/title: Spring Boot®
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: demo-java-project
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.19
  name: demo-java-project
  namespace: fannie-mae-website
spec:
  applicationImage: dev.local/demo-java-project
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: demo-java-project
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
status: {}
